[project]
name = "lab-exam"
version = "1.0.0"
description = "Ceng215 Lab Exam"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.5",
    "pyqt6>=6.10.1",
]
